### ISSUE TITLE
Github : Add simulation strategy

### ISSUE THREAD

**Issue by lfpaulin** [collaborativebioinformatics/STRdust#30]
TODO
please @DamarisLa  briefly explain you method

**Comment by DamarisLa** [comment]
STRsimulator

Manipulation of a Referencefile in order to simulate STR!!

STRsimulator
The simulator takes a haploid file as reference(.fasta) and a region file (.bed) containing information about known STR-regions as input. All of the supplied regions can be modified in

    expansion (% of regions that will randomly be positive or negative expanded [0.00-1.00]),
    mutation (% chance for a base to be substituted [0.00-1.00]),
    number of indels (X times less likely than chance for mutation to insert or delete a base [0.00-1.00]). Further can the simulation file (.fasta) be created as
    haploid [h] or
    diploid [d]. If diploid is chosen,
        the percentage of regions that should get homozygous can be set [0.00-1.00].

The simulator works on assembled genomes, as well as on only one or more assembled chromosomes, if the bed-file contains such entrances likewise (anything else could run errorfree, but will not manipulate anything, as manipulations only occur in the known regions).
